# Generated by Django 2.1 on 2019-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Barishal', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(default='Barishal', max_length=100),
        ),
    ]
