# Generated by Django 2.1 on 2019-04-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_auto_20190411_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
