# Generated by Django 2.1 on 2019-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0006_auto_20190414_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
