# Generated by Django 3.1.3 on 2020-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0011_auto_20190417_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
    ]
